import type { Metadata } from 'next';
import fs from 'fs';
import path from 'path';

export const revalidate = 3600;
export const metadata: Metadata = {
  title: 'AI Analysis | AmericasOilWatch',
  alternates: { canonical: 'https://americasoilwatch.com/analysis' },
};

export default function AnalysisPage() {
  const p = path.join(process.cwd(), 'data', 'analysis.json');
  const analysis = fs.existsSync(p) ? JSON.parse(fs.readFileSync(p, 'utf-8')) : null;

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div>
        <a href="/" className="text-xs text-oil-400 hover:underline">← Back to dashboard</a>
        <h1 className="mt-2 text-2xl font-bold text-white">AI Market Analysis</h1>
        <p className="mt-1 text-sm text-gray-400">
          Generated by Claude using EIA petroleum data, WTI price, MARAD advisories, and CREA energy research.
        </p>
      </div>
      {analysis ? (
        <div className="rounded-lg border border-oil-800 bg-oil-900/20 overflow-hidden">
          <div className="px-5 py-4 border-b border-oil-800/60">
            <p className="text-sm font-semibold text-white">{analysis.statusLine}</p>
            <p className="text-[10px] text-gray-600 mt-1">
              Generated {new Date(analysis.generatedAt).toLocaleString('en-US')} · {analysis.model}
            </p>
          </div>
          {analysis.keyPoints?.length > 0 && (
            <div className="px-5 py-4 border-b border-oil-800/60">
              <p className="text-[10px] font-mono font-semibold text-gray-500 uppercase tracking-wider mb-3">Key Points</p>
              <ul className="space-y-2">
                {analysis.keyPoints.map((pt: string, i: number) => (
                  <li key={i} className="flex items-start gap-2 text-sm text-gray-300">
                    <span className="text-oil-400 flex-shrink-0 mt-0.5">›</span>
                    {pt}
                  </li>
                ))}
              </ul>
            </div>
          )}
          <div className="px-5 py-4 prose-article">
            {analysis.fullAnalysis.split('\n\n').map((para: string, i: number) => (
              <p key={i} className="text-sm text-gray-300 leading-relaxed mb-3">{para}</p>
            ))}
          </div>
        </div>
      ) : (
        <div className="rounded-lg border border-oil-800 bg-oil-900/20 px-5 py-8 text-center">
          <p className="text-gray-500 text-sm">Analysis not yet generated.</p>
          <p className="text-gray-600 text-xs mt-1">Run: <code className="font-mono">npm run analyze</code></p>
        </div>
      )}
    </div>
  );
}
