import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Methodology | AmericasOilWatch' };
export default function MethodologyPage() {
  return (
    <div className="max-w-3xl mx-auto space-y-8">
      <div>
        <a href="/" className="text-xs text-oil-400 hover:underline">← Back to dashboard</a>
        <h1 className="mt-2 text-2xl font-bold text-white">Methodology</h1>
      </div>
      <div className="prose-article space-y-6 text-sm text-gray-400">
        <section>
          <h2 className="text-white">Data Sources</h2>
          <ul>
            <li><strong>WTI Crude Price:</strong> EIA API v2 — weekly spot price series RWTC, Cushing Oklahoma delivery</li>
            <li><strong>US Petroleum Stocks:</strong> EIA Weekly Petroleum Status Report — commercial crude, gasoline, distillates, SPR</li>
            <li><strong>US Retail Prices:</strong> EIA weekly retail gasoline and diesel survey (Monday survey, published Monday PM)</li>
            <li><strong>Brent Crude:</strong> ICE Brent front-month via public pricing feeds</li>
            <li><strong>Maritime Advisories:</strong> US Maritime Administration (MARAD) listing pages</li>
            <li><strong>Energy Research:</strong> Centre for Research on Energy and Clean Air (CREA) RSS feed</li>
          </ul>
        </section>
        <section>
          <h2 className="text-white">Update Frequency</h2>
          <p>EIA data is updated weekly — crude stocks on Wednesdays, retail prices on Mondays. The pipeline runs daily at 05:00 UTC to pick up the latest available data. AI analysis is regenerated on each successful data fetch.</p>
        </section>
        <section>
          <h2 className="text-white">Producer Data</h2>
          <p>Production figures for non-US countries (Canada, Brazil, Guyana, etc.) are editorial estimates based on IEA Monthly Oil Market Report, OPEC MOMR, and national regulator releases. These are updated less frequently than US EIA data and should be treated as approximate figures.</p>
        </section>
        <section>
          <h2 className="text-white">AI Analysis</h2>
          <p>Analysis is generated by Claude (Anthropic) using the latest fetched data. It is not financial advice. The model is instructed to cite specific numbers and avoid speculation beyond the data. Analysis is regenerated daily when new data is available.</p>
        </section>
        <section>
          <h2 className="text-white">Chokepoint Risk Ratings</h2>
          <p>Risk ratings are editorial assessments updated manually based on news sources, MARAD advisories, and geopolitical developments. They do not update automatically. Normal / Elevated / High / Critical follows the same framework as EuroOilWatch and UKOilWatch.</p>
        </section>
      </div>
    </div>
  );
}
